CREATE TABLE PERSON (
	PERSON_ID INTEGER,
	NAME VARCHAR,
	AGE INTEGER,
	ROLE VARCHAR,
	GROUP_ID INTEGER);
CREATE TABLE PERSON_GROUP (
	GROUP_ID INTEGER,
	NAME VARCHAR);
INSERT INTO PERSON_GROUP (GROUP_ID, NAME) VALUES (1, 'TEAM ALPHA');
INSERT INTO PERSON_GROUP (GROUP_ID, NAME) VALUES (2, 'TEAM BRAVO');
INSERT INTO PERSON_GROUP (GROUP_ID, NAME) VALUES (3, 'TEAM CHARLIE');
